package Encryption;

import sun.misc.BASE64Decoder;

import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.security.*;
import javax.crypto.*;

public class CipherServer {

    public static void main(String[] args) throws Exception {
        int port = 7999;
        ServerSocket server = new ServerSocket(port);
        Socket s = server.accept();
        System.out.println("Server: successfully connected");

        // YOU NEED TO DO THESE STEPS:
        // -Read the key from the file generated by the client.
        String keyFile = "/Users/drakezhou/Desktop/2150 ISP/Final Project/project_skeleton/Encryption/keyFile.txt";
        ObjectInputStream in = new ObjectInputStream(s.getInputStream());
        Key scrtKey = (Key) in.readObject();

        // -Use the key to decrypt the incoming message from socket s.
        Cipher decrypt = Cipher.getInstance("DES/ECB/PKCS5Padding");
        decrypt.init(Cipher.DECRYPT_MODE, scrtKey);
        CipherInputStream cipherInputStream = new CipherInputStream(s.getInputStream(), decrypt);

        // -Print out the decrypt String to see if it matches the orignal message.
        StringBuilder message = new StringBuilder();
        int read = cipherInputStream.read();
        try {
            while (read != -1) {
                message.append((char) read);
                read = cipherInputStream.read();
            }
        } catch (Exception ignored){}

        // -Print out the decrypt String to see if it matches the orignal message.
        System.out.println("Server: Message = " + message);
    }
}